/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as IniciarSesionRouteImport } from './routes/iniciar-sesion'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAnalisisRouteImport } from './routes/app/analisis'
import { Route as AppCalendarioRouteImport } from './routes/app/calendario'
import { Route as AppClientesRouteImport } from './routes/app/clientes'
import { Route as AppCopiesRouteImport } from './routes/app/copies'
import { Route as AppCorreosRouteImport } from './routes/app/correos'
import { Route as AppEditorRouteImport } from './routes/app/editor'
import { Route as AppEstrategiaRouteImport } from './routes/app/estrategia'
import { Route as AppLeadsRouteImport } from './routes/app/leads'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppScriptsRouteImport } from './routes/app/scripts'
import { Route as AppUsuariosRouteImport } from './routes/app/usuarios'
import { Route as AppClientesIndexRouteImport } from './routes/app/clientes/index'
import { Route as AppClientesClientIdRouteImport } from './routes/app/clientes/$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciarSesionRoute = IniciarSesionRouteImport.update({
  id: '/iniciar-sesion',
  path: '/iniciar-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalisisRoute = AppAnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCopiesRoute = AppCopiesRouteImport.update({
  id: '/copies',
  path: '/copies',
  getParentRoute: () => AppRoute,
} as any)
const AppCorreosRoute = AppCorreosRouteImport.update({
  id: '/correos',
  path: '/correos',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorRoute = AppEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppRoute,
} as any)
const AppEstrategiaRoute = AppEstrategiaRouteImport.update({
  id: '/estrategia',
  path: '/estrategia',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppScriptsRoute = AppScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppClientesClientIdRoute = AppClientesClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AppClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registro': typeof RegistroRoute
  '/app/analisis': typeof AppAnalisisRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/copies': typeof AppCopiesRoute
  '/app/correos': typeof AppCorreosRoute
  '/app/editor': typeof AppEditorRoute
  '/app/estrategia': typeof AppEstrategiaRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/scripts': typeof AppScriptsRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/app/clientes/$clientId': typeof AppClientesClientIdRoute
  '/app/clientes/': typeof AppClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registro': typeof RegistroRoute
  '/app/analisis': typeof AppAnalisisRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/copies': typeof AppCopiesRoute
  '/app/correos': typeof AppCorreosRoute
  '/app/editor': typeof AppEditorRoute
  '/app/estrategia': typeof AppEstrategiaRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/scripts': typeof AppScriptsRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app': typeof AppIndexRoute
  '/app/clientes/$clientId': typeof AppClientesClientIdRoute
  '/app/clientes': typeof AppClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registro': typeof RegistroRoute
  '/app/analisis': typeof AppAnalisisRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/copies': typeof AppCopiesRoute
  '/app/correos': typeof AppCorreosRoute
  '/app/editor': typeof AppEditorRoute
  '/app/estrategia': typeof AppEstrategiaRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/scripts': typeof AppScriptsRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/app/clientes/$clientId': typeof AppClientesClientIdRoute
  '/app/clientes/': typeof AppClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/iniciar-sesion'
    | '/registro'
    | '/app/analisis'
    | '/app/calendario'
    | '/app/clientes'
    | '/app/copies'
    | '/app/correos'
    | '/app/editor'
    | '/app/estrategia'
    | '/app/leads'
    | '/app/reports'
    | '/app/scripts'
    | '/app/usuarios'
    | '/app/'
    | '/app/clientes/$clientId'
    | '/app/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/iniciar-sesion'
    | '/registro'
    | '/app/analisis'
    | '/app/calendario'
    | '/app/copies'
    | '/app/correos'
    | '/app/editor'
    | '/app/estrategia'
    | '/app/leads'
    | '/app/reports'
    | '/app/scripts'
    | '/app/usuarios'
    | '/app'
    | '/app/clientes/$clientId'
    | '/app/clientes'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/iniciar-sesion'
    | '/registro'
    | '/app/analisis'
    | '/app/calendario'
    | '/app/clientes'
    | '/app/copies'
    | '/app/correos'
    | '/app/editor'
    | '/app/estrategia'
    | '/app/leads'
    | '/app/reports'
    | '/app/scripts'
    | '/app/usuarios'
    | '/app/'
    | '/app/clientes/$clientId'
    | '/app/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  IniciarSesionRoute: typeof IniciarSesionRoute
  RegistroRoute: typeof RegistroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciar-sesion': {
      id: '/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof IniciarSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analisis': {
      id: '/app/analisis'
      path: '/analisis'
      fullPath: '/app/analisis'
      preLoaderRoute: typeof AppAnalisisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendario': {
      id: '/app/calendario'
      path: '/calendario'
      fullPath: '/app/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copies': {
      id: '/app/copies'
      path: '/copies'
      fullPath: '/app/copies'
      preLoaderRoute: typeof AppCopiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/correos': {
      id: '/app/correos'
      path: '/correos'
      fullPath: '/app/correos'
      preLoaderRoute: typeof AppCorreosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor': {
      id: '/app/editor'
      path: '/editor'
      fullPath: '/app/editor'
      preLoaderRoute: typeof AppEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estrategia': {
      id: '/app/estrategia'
      path: '/estrategia'
      fullPath: '/app/estrategia'
      preLoaderRoute: typeof AppEstrategiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scripts': {
      id: '/app/scripts'
      path: '/scripts'
      fullPath: '/app/scripts'
      preLoaderRoute: typeof AppScriptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/': {
      id: '/app/clientes/'
      path: '/'
      fullPath: '/app/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/app/clientes/$clientId': {
      id: '/app/clientes/$clientId'
      path: '/$clientId'
      fullPath: '/app/clientes/$clientId'
      preLoaderRoute: typeof AppClientesClientIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
  }
}

interface AppClientesRouteChildren {
  AppClientesClientIdRoute: typeof AppClientesClientIdRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesClientIdRoute: AppClientesClientIdRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppRouteChildren {
  AppAnalisisRoute: typeof AppAnalisisRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppCopiesRoute: typeof AppCopiesRoute
  AppCorreosRoute: typeof AppCorreosRoute
  AppEditorRoute: typeof AppEditorRoute
  AppEstrategiaRoute: typeof AppEstrategiaRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScriptsRoute: typeof AppScriptsRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalisisRoute: AppAnalisisRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppCopiesRoute: AppCopiesRoute,
  AppCorreosRoute: AppCorreosRoute,
  AppEditorRoute: AppEditorRoute,
  AppEstrategiaRoute: AppEstrategiaRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppReportsRoute: AppReportsRoute,
  AppScriptsRoute: AppScriptsRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  IniciarSesionRoute: IniciarSesionRoute,
  RegistroRoute: RegistroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
